### ISSUE TITLE
Frontend is not fetching data

### ISSUE THREAD

**Issue by Purva-Chaudhari** [xavier-romero/kurtosis-blockscout#1]
I have deployed kurtosis cdk on sepolia. The backend looks functioning well 
<img width="1537" alt="image" src="https://github.com/xavier-romero/kurtosis-blockscout/assets/48947123/2d69286c-79e8-419d-8bf9-1fdf6d49fc91">

But on frontend I keep seeing "No Data"
<img width="1453" alt="image" src="https://github.com/xavier-romero/kurtosis-blockscout/assets/48947123/ea48eee6-8519-479e-936b-a6e156a53c36">

(I tried deploying it separately as well through this repo, I still face the issue. In separate deployment, the backend is sometimes not deployed, I think i should increase wait time for it maybe.)

But when deployed through kurtosis I see backend running well but frontend still unable to fetch data in any section. Could you please help!

**Comment by xavier-romero** [comment]
@Purva-Chaudhari could you open developer tools on the frontend (ctrl-shift-i on most browsers) and check the Console when loading o reloading it? There might be useful errors that can help us to understand what's happening.

**Comment by Purva-Chaudhari** [comment]
Oh My console looks like this . Looks like connection issue with the apis
<img width="1728" alt="image" src="https://github.com/xavier-romero/kurtosis-blockscout/assets/48947123/a7d9853c-22ca-40f6-a9c8-f5d25d00bca5">

**Comment by Purva-Chaudhari** [comment]
I have disabled CORS and CSP temporarily on chrome, I still see

<img width="644" alt="image" src="https://github.com/xavier-romero/kurtosis-blockscout/assets/48947123/01c874ef-01aa-4ee5-af76-c588bc1a2c39">

**Comment by xavier-romero** [comment]
Sorry, are you accessing this through a remote URL? Could you share the exact URL you're using to access Frontend?

**Comment by Purva-Chaudhari** [comment]
Yes I have set it up in VM and run it on my local. backend works separately, but here i see issue here. 

Let me try to solve connection issues and update

**Comment by Purva-Chaudhari** [comment]
My frontend url is - http://91.134.86.17:50101/
Backend - http://91.134.86.17:33084/

**Comment by xavier-romero** [comment]
This won't work, at least as it is right now. The package is meant to be run and accessed locally, so the frontend sends you urls to access backend data through 127.0.0.1, which obviously will only work if you open the browser in the same machine that is running Kurtosis.
If you make the required modifications to get it to work remotely please feel free to open a PR.

**Comment by Purva-Chaudhari** [comment]
Sounds good, thank you so much !

**Comment by Purva-Chaudhari** [comment]
Hi @xavier-romero was just curious, the frontend was working for me when I deployed on local chain. On sepolia I get this issue. Both the cases I have remote url only

**Comment by xavier-romero** [comment]
@Purva-Chaudhari do you have the remote url for the local l1 so I can take a look?
And also the params set for both cases please

**Comment by xavier-romero** [comment]
Ok, I got it partially working, you need to add an extra param: blockscout_public_ip
Set your public ip address on this param, and it will work. The real time update on the web does not work because the WS is not proxied correctly, or I miss somethjing... but as far as you're ok doing F5, the everything else seems to work ok.

**Comment by Purva-Chaudhari** [comment]
Thank you very much for looking into it, I am trying it out

Sorry I don't have local deployment url working atm
