### ISSUE TITLE
http://127.0.0.1:50101/node-api/proxy/api/v2/stats

### ISSUE THREAD

**Issue by ChainCoderX** [xavier-romero/kurtosis-blockscout#6]
How to fix the problem with public ip address ?

I follow the link:
https://docs.polygon.technology/cdk/build/quickstart/breakdown-deployment/#deploy-blockscout-stack

**Comment by ChainCoderX** [comment]
try the following parameters, but failed.

https://github.com/0xPolygon/kurtosis-cdk/blob/main/params.yml
 blockscout_public_port: 50101
 blockscout_public_ip: 43.198.54.207

**Comment by xavier-romero** [comment]
Did you set `blockscot_backend_port`?

From [README](https://github.com/xavier-romero/kurtosis-blockscout/blob/main/README.md):
`blockscot_backend_port: if you want to expose blockscout to be accessed remotely (you've set blockscout_public_ip), you need to set a port for backend as well`

Try setting a value for this extra var, for instance:
```
blockscout_public_ip: 43.198.54.207
blockscout_public_port: 50101
blockscout_public_port: 50102
```
I think that should be enough

**Comment by atisheksingh** [comment]
hey @xavier-romero  can you  share a ngnix file for the reference , we are having troubles mapping port

**Comment by xavier-romero** [comment]
> hey [@xavier-romero](https://github.com/xavier-romero) can you share a ngnix file for the reference , we are having troubles mapping port

Sorry, I don't get you, the stack does not use any nginx, but if you need one you can set one in front of course.

**Comment by atisheksingh** [comment]
we are running everything on the same server frontend and backend , we are using nginx to expose the static ip and port to external url , but we are getting errors in the frontend to consume backend api  , please check the image below , can you help us with the issue .

![Image](https://github.com/user-attachments/assets/a531b1de-07f5-4fd4-a413-f4decb0a8ebf)

**Comment by xavier-romero** [comment]
Please, try these steps:

1. Be aware of the ip of yout server, let's call it <server_ip>
2. Configure the required vars, for instance:
 	- `blockscout_public_ip`: <server_ip>
 	- `blockscout_public_port`: 50101
  	- `blockscot_backend_port`: 50102
3. Once deployed, from a remote computer:
 	- Be sure you have connectivity to your server:
               - `ping <server_ip>`
               - `telnet <server_ip> 50101`
 	- If these don't work, you have an issue with your network/firewall configuration.
4. Access `http://<server_ip>:50101`

If you passed the check, for setting nginx in front you should get help from someone with specific nginx knowledge. I'd say it should not be difficult, as long as:
1. The IP/DNS_NAME you publish on nginx matches with the `blockscout_public_ip`
2. You publish both ports (`blockscout_public_port` and `blockscot_backend_port`) as they are, if you remap them, it won't work
